# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Color it!' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Color it!


  
  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

  pod 'Alamofire', '~> 5.2'

  pod 'Kingfisher', '~> 5.0'

  pod 'AlamofireImage', '~> 4.1'


end
